name: TmukLabb3

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x'] 

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
		#Restores
      - name: Restore dependencies Server
        run: dotnet restore ./Server/Server.sln
      - name: Restore dependencies Client
        run: dotnet restore ./Client/Client.sln
		#Checks Version
      - name: dotnet version
        run: dotnet --version
		#Builds
      - name: Build ./Server
        run: dotnet build ./Server/Server.sln --no-restore
      - name: Build ./Client
        run: dotnet build ./Client/Client.sln --no-restore
		#Tests
      - name: Test ./Server
        run: dotnet test ./Server/Server.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./Server/coveragereport/
      - name: Test ./Client 
        run: dotnet test ./Client/Client.sln --verbosity normal --collect:"XPlat Code Coverage" --results-directory .Client/coveragereport/
		#Linters
      - name: Linter ./Server
        run: dotnet format ./Server/Server.sln
      - name: Linter ./Client
        run: dotnet format ./Client/Client.sln
		#Code coverage
	  - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coveragereport/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'