name: TmukLabb3

on: [push]

jobs:
  Server:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x'] 

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore ./Server/Server.sln

      - name: dotnet version
        run: dotnet --version

      - name: Build Server
        run: dotnet build ./Server/Server.sln --no-restore

      - name: Test Server
        run: dotnet test ./Server/Server.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./Server/coveragereport/

      - name: Linter Server
        run: dotnet format ./Server/Server.sln --verify-no-changes
          
      - name: ReportGenerator Server
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.15
        with:
          reports: 'Server/coveragereport/**/coverage.cobertura.xml'
          targetdir: 'Server/coveragereport'
          reporttypes: 'HtmlSummary'

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ServerCoverageReport
          path: Server/coveragereport\summary.html

  Client:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x'] 

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore ./Client/Client.sln

      - name: dotnet version
        run: dotnet --version

      - name: Build Client
        run: dotnet build ./Client/Client.sln --no-restore

      - name: Test Client 
        run: dotnet test ./Client/Client.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./Client/coveragereport/

      - name: Linter Client
        run: dotnet format ./Client/Client.sln --verify-no-changes

      - name: ReportGenerator Client
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.15
        with:
          reports: 'Client/coveragereport/**/coverage.cobertura.xml'
          targetdir: 'Client/coveragereport'
          reporttypes: 'HtmlSummary'

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ClientCoverageReport
          path: Client/coveragereport/summary.html